title: Samantha Pua
logo: "/images/dp.jpeg?raw=true" # your photo (or logo) here
description: > 
 | Data Analytics | Data Science | Business Intelligence |
  <br>
  <br>
 Check out: <a href="https://www.linkedin.com/in/puaxuanyun/">LinkedIn</a> | <a href="https://github.com/samanthapua">GitHub</a> |

  

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

