title: Samantha Pua
logo: "/images/dp.jpeg?raw=true" # your photo (or logo) here
description: > 
 Data Analytics | Data Science | Business Intelligence | Robotics Process Automation | Process Optimization |
  <br>
  <br>
 <a href="https://www.linkedin.com/in/puaxuanyun/">LinkedIn</a> | <a href="https://github.com/samanthapua">GitHub</a> | <a href="https://public.tableau.com/app/profile/samantha.pua/vizzes">Tableau</a>

  

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

